# Lista de Ejercicios

1.Definimos:
 * `x <- c(5, 2, 1, 4); y <- rep(1, 5)`

Predice las soluciones antes de escribir los comandos 

a)
 * `sum(x)`

In [1]:
# Nos dará la suma de los elementos de x.

 * `range(x)`

In [2]:
# Nos dará el menor y el mayor elemento de x.

 * `sum(y)`

In [3]:
# Nos dará la suma de elmentos de y.

 * `length(y)`

In [4]:
# Nos dará la longitud del vector y.

b) 
 * `c(x, y, 13)`

In [5]:
# Concatenará los elementos de x, y con el número 13.

c) 
 * `x[4] * y[2]`

In [6]:
# Multilplicará el elemento de lugar cuatro de x, con el elemento de
# lugar dos de y.

 * `x[2:4] + x[1:3]`

In [7]:
# Sumará los elementos de x, desde el lugar dos hasta el lugar cuatro con 
# los de lugar uno, dos y tres también de x.

d) 
 * `x <= 2`

In [8]:
# Compara cada elemento de x con 2, devolviéndonos un vector lógico 
# con TRUE cuando x es menor o igual a 2, y FALSE en otros casos.

 * `x[x <= 2]`

In [9]:
# Nos devuelve el valor de x en las posiciones donde el vector lógico que
# resulta de x <= 2 es TRUE.

 * `x[(x != 5) & (x > 3)]`

In [10]:
# Nos retornará los valores donde el vector lógico (x != 5) & (x < 3) es TRUE, 
# dicho vector lógico será TRUE cuando cada elemen to de x sea
# diferente de 5 y menor a 3.

e) 
 * `rep(1:4,2)`

In [11]:
# Repetirá dos veces el vector 1:4

 * `rep(1:4,each = 2)`

In [12]:
# Cada elemento será repetido dos veces.

 * `rep(1:4,c(2, 1, 2, 1))`

In [13]:
# Cada elemento del primer argumento de la función rep() se repetirá tantas veces como
# indica cada elemento del segundo argumento, en una correspondencia de uno a uno.

 * `rep(1:4,each = 2, len = 10)`

In [14]:
# Cada elemento del vector 1:4 se repetirá dos vececs hasta que el vector resultante alcance
# la longitud de diez.

f) 
 * `2:3^2`

In [15]:
# Enlistará los números desde dos hasta 3^2.

 * `seq(2, -3) * c(-1, 1)`

In [16]:
# Luego de enlistar los número enteros desde dos hasta -3, se multiplicará a cada uno de 
# ellos, de manera alternada, por -1 y 1; donde debido a la diferencia de longitudes en
# los vectores que hacen de facotres, R hará uso del recycling.

2.
 * Describe importantes diferencias entre las estructuras fundamentales de $R$: $\texttt{vectores, matrices, arrays}$ y $\texttt{listas}$. Usa ejemplos para demostrar esas diferencias.

In [17]:
# Vectores:
# Un vector es una estructura de datos básica de R, que contiene elementos del mismo tipo. 
# Los tipos de datos pueden ser logical, integer, double, character, complex or raw.
(a <- c(2, 3, 5, 7, 11)) # es una vector del tipo integer, mientras que 
(b <- c("build", "your", "wings")) # es del tipo character.

# Matrices:
# Las matrices son vectores especiales en , ellas no son una clase separada de objetos, 
# sino un vector pero ahora con dimensiones añadidas a ella. Las matrices poseen filas y 
# columnas.
(my_matrix <- matrix(c(2, 3, 5, 7, 11, 13), nrow = 2, ncol = 3))

# Arrays:
# Los vectores están altamente relacionados con un clase más grande de objetos, los arrays. 
# Los arrays poseen dos importantes características: contienen un solo tipo de dato, y los
# arrays poseen dimensión. La dimensión del array  determina el tpo de array. Un vector 
# posee una dimensión. Un array con dos dimensiones es una matriz y aquellos que tengan 
# más de dos dimenciones es simplemente llamado array.
(my_array <- array(1:24, dim = c(3, 4, 2)))


# Listas:
# En R las listas actúan como "contenedores". A diferencia de los vectores atómicos ellas 
# no están rectringidas a un único y pueden abarcar cualquier tipo de datos. Las listas
# son a veces llamadas vectores recursivos, pues una lista puede contener a otras listas. 
# Esta es la principal diferencia con los vectores atómicos.
(my_list <- list(1, "a", 2+ 3i, TRUE))


[1]  2  3  5  7 11

[1] "build" "your"  "wings"

[,1] [,2] [,3]
[1,] 2    5    11  
[2,] 3    7    13

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

, , 2

     [,1] [,2] [,3] [,4]
[1,]   13   16   19   22
[2,]   14   17   20   23
[3,]   15   18   21   24

[[1]]
[1] 1

[[2]]
[1] "a"

[[3]]
[1] 2+3i

[[4]]
[1] TRUE

 * Explicar las diferencias entre las funciones $\texttt{rbind()$, $cbind()}$ y $\texttt{merge()}$ para combinar dos estructuras de dos dimensiones en $R$. Usa ejemplos para demostrar esas diferencias.


In [18]:
# rbind():
# Esta función concatena vectores para formar una matriz enlistándolos fila por fila.
rbind(1:14, 1:7)

# cbind():
# Tiene la misma labor que la función rbind() solo que la concatenación la hace columna
# por columna

# merge():
# Cuando dos data frames comparten columnas, se pueden fusionar usando la función mege(), 
# la cual provee una gran variedad de opciones para realizar combinaciones de diversos
# estilos. Para unir dos data frames es necesario especificar qué columnas contienen los 
# valores clave pra que coincidan. Por defecto, la función merge() utiliza todas las
# funcines comunes de los dos data frame, pero más comúnmente solo querrá usar una 
# única columna de ID compartido.
my_dataframe <- data.frame(
  x = letters[1:5],
  y = rnorm(5),
  z = runif(5) > 0.5
)
my_dataframe2 <- data.frame( 
  z = rlnorm(5), 
  y = sample(5), 
  x = letters[3:7]
)
merge(my_dataframe, my_dataframe2, by = "x")
# Hemos especificado que la columna x contiene nuestros IDs usando el argumento "by". 


[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 1    2    3    4    5    6    7    8    9    10    11    12    13    14   
[2,] 1    2    3    4    5    6    7    1    2     3     4     5     6     7

x y.x        z.x   z.y      y.y
1 c -1.1114858 FALSE 2.930147 1  
2 d -0.5297717 FALSE 1.186634 3  
3 e  1.2211796 FALSE 1.100507 4

3)

a)  Construye  y almacena una matriz $4 \times 2$ que se completa  por  fila con los valores $4.3, 3.1, 8.2, 8.2, 3.2, 0.9, 1.6$ y $6.5$, en ese orden.


In [19]:
A <- matrix(data = c(4.3, 3.1, 8.2, 8.2, 3.2, 0.9, 1.6, 6.5), 
            nrow = 4, ncol = 2, byrow = TRUE)
A

[,1] [,2]
[1,] 4.3  3.1 
[2,] 8.2  8.2 
[3,] 3.2  0.9 
[4,] 1.6  6.5

b) Confirma que las dimensiones de la matriz de (a) son $3 \times  2$ si se elimina una fila.


In [20]:
dim(A[-1,])  # hemos eliminado la primera fila

[1] 3 2

c) Sobrescribe la segunda columna de la matriz de (a) con esa misma columna ordenada de menor a mayor.

In [21]:
(A[, 2] <- sort(A[, 2]))

[1] 0.9 3.1 6.5 8.2

d) ¿Qué devuelve $R$ si se elimina la cuarta fila y la primera columna de (c)?. Utiliza $\texttt{matrix}$ para asegurar que el resultado sea una matriz de una sola columna, en lugar de un vector.

In [22]:
A[-4, -1]

[1] 0.9 3.1 6.5

e) Guarde los cuatro elementos inferiores de (c) como una nueva matriz $2\times 2$.


In [23]:
(B <- A[3:4,])
dim(B)

[,1] [,2]
[1,] 3.2  6.5 
[2,] 1.6  8.2

[1] 2 2

f) Sobrescribe en este orden los elementos de (c) en las posiciones $(4, 2), (1, 2), (4, 1)$ y $(1, 1)$ con $\frac{1}{2}$ de los dos valores de la diagonal de (e).


In [24]:
A[c(4, 1), 2:1] <- (-0.5)*diag(B)
A

[,1] [,2]
[1,] -4.1 -4.1
[2,]  8.2  3.1
[3,]  3.2  6.5
[4,] -1.6 -1.6

4.Calcula lo siguiente:

$$\dfrac{2}{7}\begin{bmatrix}
        1 & 2  \\[0.3em]
        2 &  4 \\[0.3em]
        7 & 6 
     \end{bmatrix} - \begin{bmatrix}
        10 & 20  \\[0.3em]
        30 &  40 \\[0.3em]
        50 & 60 
\end{bmatrix}$$

In [25]:
(A <- cbind(c(1, 2, 7), c(2, 4, 6)))
(B <- matrix(data = c(1, 2, 3, 4, 5, 6), nrow = 3, ncol = 2, byrow = TRUE))
(2/7)*A - 10* B

[,1] [,2]
[1,] 1    2   
[2,] 2    4   
[3,] 7    6

[,1] [,2]
[1,] 1    2   
[2,] 3    4   
[3,] 5    6

[,1]       [,2]     
[1,]  -9.714286 -19.42857
[2,] -29.428571 -38.85714
[3,] -48.000000 -58.28571

5.Almacena estas dos matrices:

$$A = \begin{bmatrix}
1 \\[0.3em]
2 \\[0.3em]
7 
\end{bmatrix}\qquad B = \begin{bmatrix}
3 \\[0.3em]
4 \\[0.3em]
8 
\end{bmatrix}$$

 ¿Cuál de las siguientes multiplicaciones son posibles?. Para los que son, calcula el resultado.


In [26]:
(A <- matrix(data = c(1, 2, 7), nrow = 3, ncol = 1))
(B <- matrix(data = c(3, 4, 8), nrow = 3, ncol = 1))

[,1]
[1,] 1   
[2,] 2   
[3,] 7

[,1]
[1,] 3   
[2,] 4   
[3,] 8

$A \cdot B$

In [27]:
# No es posible calcular el resultado pues: 
ncol(A) == nrow(B) # nos da FALSE

[1] FALSE

$A^T \cdot B$

In [28]:
t(A) %*% B

[,1]
[1,] 67

$B^T \cdot (A \cdot A^T)$

In [29]:
t(B) %*% (A %*% t(A))

[,1] [,2] [,3]
[1,] 67   134  469

 $[(B\cdot B^T) + (A \cdot A^T)- 100I_3 ]^{-1}$

In [30]:
solve((B %*% t(B)) + (A %*% t(A)) - 100*diag(x = 3))

[,1]         [,2]         [,3]       
[1,] -0.007923676  0.003123274 0.007843334
[2,]  0.003123274 -0.005350239 0.011483806
[3,]  0.007843334  0.011483806 0.017584735

6.La función $\texttt{diag}$ tiene varios usos, uno de los cuales es tomar un vector como  entrada y crea una matriz cuadrada con ese vector en la diagonal. Crea una matriz  $21 \times 21$ con la secuencia de $10$ a $0$ y a $11$ (es decir, $11, 10, \dots, 1, 0, 1, \dots, 11$).


In [31]:
diag( x = c(10:0,1:11))

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,] 10   0    0    0    0    0    0    0    0    0     ⋯     0     0    
 [2,]  0   9    0    0    0    0    0    0    0    0     ⋯     0     0    
 [3,]  0   0    8    0    0    0    0    0    0    0     ⋯     0     0    
 [4,]  0   0    0    7    0    0    0    0    0    0     ⋯     0     0    
 [5,]  0   0    0    0    6    0    0    0    0    0     ⋯     0     0    
 [6,]  0   0    0    0    0    5    0    0    0    0     ⋯     0     0    
 [7,]  0   0    0    0    0    0    4    0    0    0     ⋯     0     0    
 [8,]  0   0    0    0    0    0    0    3    0    0     ⋯     0     0    
 [9,]  0   0    0    0    0    0    0    0    2    0     ⋯     0     0    
[10,]  0   0    0    0    0    0    0    0    0    1     ⋯     0     0    
[11,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[12,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[13,]  0   0    0    0    0    0    0    0    0    0     ⋯     2     0    
[14,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     3    
[15,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[16,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[17,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[18,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[19,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[20,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[21,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[22,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
      [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21]
 [1,] 0     0     0     0     0     0      0     0   
 [2,] 0     0     0     0     0     0      0     0   
 [3,] 0     0     0     0     0     0      0     0   
 [4,] 0     0     0     0     0     0      0     0   
 [5,] 0     0     0     0     0     0      0     0   
 [6,] 0     0     0     0     0     0      0     0   
 [7,] 0     0     0     0     0     0      0     0   
 [8,] 0     0     0     0     0     0      0     0   
 [9,] 0     0     0     0     0     0      0     0   
[10,] 0     0     0     0     0     0      0     0   
[11,] 0     0     0     0     0     0      0     0   
[12,] 0     0     0     0     0     0      0     0   
[13,] 0     0     0     0     0     0      0     0   
[14,] 0     0     0     0     0     0      0     0   
[15,] 4     0     0     0     0     0      0     0   
[16,] 0     5     0     0     0     0      0     0   
[17,] 0     0     6     0     0     0      0     0   
[18,] 0     0     0     7     0     0      0     0   
[19,] 0     0     0     0     8     0      0     0   
[20,] 0     0     0     0     0     9      0     0   
[21,] 0     0     0     0     0     0     10     0   
[22,] 0     0     0     0     0     0      0    11

7.Para

$$A = \begin{bmatrix}
        2 & 0 & 0  & 0    \\[0.3em]
        0 & 3 & 0 & 0     \\[0.3em]
        0 & 0 & 5 & 0      \\[0.3em]
        0 & 0 & 0 & -1           
\end{bmatrix}$$

Comprueba   que $A^{-1}\cdot A -I_4$ proporciona una matriz $4 \times 4$ de ceros.


In [32]:
(A <- rbind(c(2, 0, 0, 0), c(0, 3, 0, 0), c(0, 0, 5, 0), c(0, 0, 0, -1)))
C <- (solve(A) %*% A) - diag(x = 4)   # almacenamos la operación pedida.
B <- matrix(0, nrow = 4, ncol = 4)   # creamos a nuestra matriz de 4X4 de ceros.
identical(B, C)  # nos retorna TRUE.

[,1] [,2] [,3] [,4]
[1,] 2    0    0     0  
[2,] 0    3    0     0  
[3,] 0    0    5     0  
[4,] 0    0    0    -1

[1] TRUE

8.Usa las funciones $\texttt{matrix()}$, $\texttt{seq()}$ y $\texttt{rep()}$ para construir la matrices de Hankel $5 \times 5$.

$$M = \begin{bmatrix}
        1 & 2 & 3  & 4 & 5         \\[0.3em]
        2 & 3 & 4 & 5 & 6           \\[0.3em]
        3 & 4 & 4 & 6 & 7           \\[0.3em]
       4 & 5 & 6 & 7 & 8           \\[0.3em]
        5 & 6 & 7 & 8 & 9           
\end{bmatrix}$$

Convierte el código en una función que puede ser usado para construir matrices de dimensión $n \times n$. Usa esa función para mostrar las salida de Matrices de Hankel de orden $10 \times 10$ y $12 \times 12$.


In [33]:
# Separamos la matriz de Hankel en dos matrices: A y B.
A <- matrix(data = rep.int(1:5, times = 5), nrow = 5, byrow = TRUE) 
B <- matrix(rep(seq(from = 0, to = 4), each = 5), nrow = 5, byrow = TRUE)
A + B # Al sumar estas matrices obtenemos la matriz de Hankel.

# La generalización de las ideas del ítem a), es tomada para representar las 
# posiciones de un vector cualquiera.
# El argumento de nuestra función es la longitud del vector generador de la matriz 
# de Hankel.
my_posicions <- function(n){
A <- matrix(data = rep.int(1:n, times = n), nrow = n, byrow = TRUE)
B <- matrix(rep(seq(from = 0, to = n - 1), each = n), nrow = n, byrow = TRUE)
return (A + B)}

# La longitud del vector, que es usado como argumento, debe ser impar.
my_hankel <- function(my_vector)
{
  dimension = (1/2)*(length(my_vector) + 1)
  matrix(data = my_vector[my_posicions(dimension)], nrow = dimension, byrow = TRUE)
}

# Matriz de Henkel de orden 10
my_hankel(c(2, 3, 5, 7, 11, 13, 17, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71))

# Matriz de Henkel de orden 12
my_hankel(c(2, 3, 5, 7, 11, 13, 17, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 
            73, 79, 83, 89))


[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4    5   
[2,] 2    3    4    5    6   
[3,] 3    4    5    6    7   
[4,] 4    5    6    7    8   
[5,] 5    6    7    8    9

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]  2    3    5    7   11   13   17   23   29   31   
 [2,]  3    5    7   11   13   17   23   29   31   37   
 [3,]  5    7   11   13   17   23   29   31   37   41   
 [4,]  7   11   13   17   23   29   31   37   41   43   
 [5,] 11   13   17   23   29   31   37   41   43   47   
 [6,] 13   17   23   29   31   37   41   43   47   53   
 [7,] 17   23   29   31   37   41   43   47   53   59   
 [8,] 23   29   31   37   41   43   47   53   59   61   
 [9,] 29   31   37   41   43   47   53   59   61   67   
[10,] 31   37   41   43   47   53   59   61   67   71

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12]
 [1,]  2    3    5    7   11   13   17   23   29   31    37    41   
 [2,]  3    5    7   11   13   17   23   29   31   37    41    43   
 [3,]  5    7   11   13   17   23   29   31   37   41    43    47   
 [4,]  7   11   13   17   23   29   31   37   41   43    47    53   
 [5,] 11   13   17   23   29   31   37   41   43   47    53    59   
 [6,] 13   17   23   29   31   37   41   43   47   53    59    61   
 [7,] 17   23   29   31   37   41   43   47   53   59    61    67   
 [8,] 23   29   31   37   41   43   47   53   59   61    67    71   
 [9,] 29   31   37   41   43   47   53   59   61   67    71    73   
[10,] 31   37   41   43   47   53   59   61   67   71    73    79   
[11,] 37   41   43   47   53   59   61   67   71   73    79    83   
[12,] 41   43   47   53   59   61   67   71   73   79    83    89

9.La matriz de Hilbert $n \times n$ tiene a los elementos $(i,j)$ dados por $1/(i + j-1)$.


 * Escribe una función que muestra una matriz de Hilbert $n \times n$ como salida para entero positivo $n$.


In [2]:
# La matriz de Hilbert es la inversa de la matriz de Hankel genenrada por el vector 1:n
my_hilbert <- function(n){
  A <- matrix(data = rep.int(1:n, times = n), nrow = n, byrow = TRUE)
  B <- matrix(rep(seq(from = 0, to = n - 1), each = n), nrow = n, byrow = TRUE)
  return (1/(A + B))
}
my_hilbert(5)

[,1]      [,2]      [,3]      [,4]      [,5]     
[1,] 1.0000000 0.5000000 0.3333333 0.2500000 0.2000000
[2,] 0.5000000 0.3333333 0.2500000 0.2000000 0.1666667
[3,] 0.3333333 0.2500000 0.2000000 0.1666667 0.1428571
[4,] 0.2500000 0.2000000 0.1666667 0.1428571 0.1250000
[5,] 0.2000000 0.1666667 0.1428571 0.1250000 0.1111111

 * ¿Son todas las matrices de Hilbert invertibles?.

In [35]:
# Sí, todas las matrices de Hilbert son invertibles

 * Usa $\texttt{solve()}$ y $\texttt{qr.solve()}$ para calcular la inversa de las matrices Hilbert, por ejemplo, cuando $n = 10$.


In [3]:
solve(my_hilbert(10)) 
# solve() calcula la inversa de la matriz dada como argumento basada en el método LU
qr.solve(my_hilbert(10),tol = 0) 
#  qr.solve() calcula la inversa de la matriz dada como argumento basada en el método QR

[,1]          [,2]          [,3]          [,4]          [,5]         
 [1,]  9.999719e+01 -4.949757e+03  7.919482e+04 -6.005529e+05       2522295
 [2,] -4.949756e+03  3.266790e+05 -5.880152e+06  4.756344e+07    -208088462
 [3,]  7.919480e+04 -5.880151e+06  1.128980e+08 -9.512635e+08    4280662450
 [4,] -6.005527e+05  4.756343e+07 -9.512634e+08  8.244246e+09  -37871868827
 [5,]  2.522294e+06 -2.080884e+08  4.280662e+09 -3.787187e+10  176734991839
 [6,] -6.305679e+06  5.350810e+08 -1.123668e+10  1.009913e+11 -477183582308
 [7,]  9.608580e+06 -8.323436e+08  1.775667e+10 -1.615857e+11  771204559101
 [8,] -8.750614e+06  7.700557e+08 -1.663323e+10  1.528915e+11 -735791094422
 [9,]  4.375282e+06 -3.898391e+08  8.505604e+09 -7.883452e+10  382044919568
[10,] -9.236661e+05  8.313037e+07 -1.828875e+09  1.706955e+10  -83214282335
      [,6]          [,7]          [,8]          [,9]          [,10]        
 [1,] -6.305682e+06  9.608586e+06 -8.750620e+06  4.375286e+06 -9.236669e+05
 [2,]  5.350812e+08 -8.323439e+08  7.700561e+08 -3.898393e+08  8.313042e+07
 [3,] -1.123669e+10  1.775667e+10 -1.663324e+10  8.505608e+09 -1.828876e+09
 [4,]  1.009913e+11 -1.615857e+11  1.528915e+11 -7.883455e+10  1.706956e+10
 [5,] -4.771836e+11  7.712047e+11 -7.357912e+11  3.820450e+11 -8.321430e+10
 [6,]  1.301409e+12 -2.120813e+12  2.037577e+12 -1.064270e+12  2.330005e+11
 [7,] -2.120813e+12  3.480308e+12 -3.363622e+12  1.765901e+12 -3.883348e+11
 [8,]  2.037577e+12 -3.363622e+12  3.267520e+12 -1.723107e+12  3.804102e+11
 [9,] -1.064270e+12  1.765901e+12 -1.723107e+12  9.122340e+11 -2.020931e+11
[10,]  2.330005e+11 -3.883348e+11  3.804101e+11 -2.020931e+11  4.490964e+10

[,1]          [,2]          [,3]          [,4]          [,5]         
 [1,]  9.999763e+01 -4.949796e+03  7.919566e+04 -6.005606e+05       2522332
 [2,] -4.949794e+03  3.266822e+05 -5.880222e+06  4.756409e+07    -208091541
 [3,]  7.919557e+04 -5.880218e+06  1.128994e+08 -9.512768e+08    4280726081
 [4,] -6.005595e+05  4.756403e+07 -9.512762e+08  8.244364e+09  -37872432943
 [5,]  2.522326e+06 -2.080912e+08  4.280722e+09 -3.787241e+10  176737626224
 [6,] -6.305764e+06  5.350885e+08 -1.123685e+10  1.009928e+11 -477190694526
 [7,]  9.608718e+06 -8.323557e+08  1.775693e+10 -1.615881e+11  771216047252
 [8,] -8.750745e+06  7.700672e+08 -1.663348e+10  1.528938e+11 -735802046037
 [9,]  4.375350e+06 -3.898451e+08  8.505733e+09 -7.883571e+10  382050600435
[10,] -9.236809e+05  8.313167e+07 -1.828903e+09  1.706981e+10  -83215518397
      [,6]          [,7]          [,8]          [,9]          [,10]        
 [1,] -6.305784e+06  9.608755e+06 -8.750784e+06  4.375372e+06 -9.236858e+05
 [2,]  5.350897e+08 -8.323580e+08  7.700697e+08 -3.898465e+08  8.313200e+07
 [3,] -1.123686e+10  1.775696e+10 -1.663352e+10  8.505756e+09 -1.828909e+09
 [4,]  1.009929e+11 -1.615883e+11  1.528940e+11 -7.883586e+10  1.706985e+10
 [5,] -4.771909e+11  7.712167e+11 -7.358029e+11  3.820511e+11 -8.321566e+10
 [6,]  1.301428e+12 -2.120845e+12  2.037609e+12 -1.064286e+12  2.330042e+11
 [7,] -2.120844e+12  3.480361e+12 -3.363673e+12  1.765928e+12 -3.883407e+11
 [8,]  2.037607e+12 -3.363671e+12  3.267568e+12 -1.723133e+12  3.804158e+11
 [9,] -1.064285e+12  1.765927e+12 -1.723132e+12  9.122472e+11 -2.020961e+11
[10,]  2.330039e+11 -3.883404e+11  3.804156e+11 -2.020960e+11  4.491027e+10

10.
 * Genere una matriz tridimensional con dimensiones $4 \times 3 \times 2$ que contengan los números del $1$ al $24$.


In [ ]:
(my_array <- array( data = 1:24, dim = c(4, 3, 2)))

 * Extraiga la última porción $\texttt{(a[,, 2])}$ del array y guárdela como una matriz $M$.


In [ ]:
(M <- my_array[, , 2])

 * Genera una nueva matriz de dimensiones $4 \times 3 \times 3$ que es idéntica a la matriz anterior, pero añade la matriz $M$ como la tercera entrada en la tercera dimensión.


In [ ]:
array(data = c(my_array, M), dim = c(4, 3, 3))

11.Crea una matriz aleatoria entera $6 \times 10$ escogidos entre $1,2,\dots, 10$, ejecutando las siguientes línes de código:

`set.seed(75)`

`aMat <- matrix( sample(10, size=60, replace=T), nr=6)`

a) Encuentra el número de entradas en cada fila que son mayores que $4$.

In [ ]:
set.seed(75)
aMat <- matrix(data = sample(1:10, size = 60, replace = TRUE), nrow = 6, ncol = 10)
aMat

mayor <- function(x) sum(x >  4) # Calculamos cuántos elementos de x son mayores a 4.
apply(aMat, 1, mayor)

b) ¿Qué filas contienen exactamente dos ocurrencias del número $7$?


In [ ]:
ocurrencias <- function(x) sum(x == 7) # Calculamos cuántas elementos son iguales a 7 en x.
which(apply(aMat, 1, ocurrencias) == 2)

c) Encuentra aquellos pares de columnas cuyo total (sobre ambas columnas) es mayor que $75$. La respuesta debería ser una matriz con dos columnas; así, por ejemplo, la fila $(1, 2)$ en la matriz de salida significa que la suma de las columnas $1$ y $2$ en la matriz original es mayor que $75$. Se permite repetir una columna; por ejemplo, la matriz de salida final podría contener las filas $(1, 2)$, $(2, 1)$ y $(2, 2)$.

¿Qué sucede si no se permiten repeticiones? Entonces, solo se permitiría $(1, 2)$ de $(1, 2)$, $(2, 1)$ y $(2, 2)$?.


In [ ]:
# Si se permite repetir columnas:
vector_sum_col <- apply(aMat, 2, sum) 
# Almacenamos los valores de la suma de elementos de cada columna.
suma_por_elementos <- function(x) x + vector_sum_col  
# x es sumado con vector_sum_col, y así aprovecharemos la vectorización de R.
superior <- function (x) sapply(x, suma_por_elementos) 
# Nos devuelve una matriz de todas las posibles sumas de elementos de vector_sum_col
which(sapply(vector_sum_col, superior) > 75, arr.ind = TRUE)

# Si no se permite repetir columnas
matriz_pedida <- sapply(vector_sum_col, superior) > 75
# Almacenamos la matriz con valores lógicos
matriz_triangular <- lower.tri(sapply(vector_sum_col, superior) > 75)
# Buscamos que la parte triangular inferior de la matriz sea considerada, por lo usamos
# lower.tri()
which(matriz_pedida == matriz_triangular & matriz_pedida == TRUE, arr.ind = TRUE)
# arr.ind nos devuelve el índice según la posición espacial que ocupa en el array.